name: 08 Secrets And Variables

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    env:
      DEPLOYMENT_ENV: 'production'  # Define a workflow-level environment variable

    steps:
    - name: Build
      run: |
        # Build your application here
        echo "Building the application"
        echo ${{ secrets.API_KEY }}
        echo ${{ env.DEPLOYMENT_ENV }}
        echo $SECRET_API_KEY
        echo $CONFIG_VARIABLE
        echo $STEPS_USERNAME
        echo ${{ vars.USERNAME }}
      env:
        SECRET_API_KEY: ${{ secrets.API_KEY }}  # Access a secret as an environment variable
        STEPS_USERNAME: ${{ vars.USERNAME }}
        CONFIG_VARIABLE: ${{ env.DEPLOYMENT_ENV }}  # Use a workflow-level environment variable

    - name: Deploy
      run: |
        # Deploy your application using the secrets and variables
        echo "Global job variable ${{ env.DEPLOYMENT_ENV }}"
        echo "Variable from previous step ${CONFIG_VARIABLE} environment"
        echo "Variable from this step ${CONFIG_VARIABLE2} environment"
        echo "Local step variable ${ANOTHER_VARIABLE}"
        echo "Secret print ${{ secrets.API_KEY }}"
        echo "Step's secret variable ${SECRET_API_KEY}"
      env:
        SECRET_API_KEY: ${{ secrets.API_KEY }}
        CONFIG_VARIABLE2: ${{ env.DEPLOYMENT_ENV }}  # Use a workflow-level environment variable
        ANOTHER_VARIABLE: 'Some value'  # Define a variable directly in the workflow
